# Site settings
title: ERC Abay Abay Customs Brokerage
email: emmanabayabay@yahoo.com
description: > # this means to ignore newlines until "url:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "" # the subpath of your site, e.g. /blog/
url: "https://www.ercabayabay.com" # the base hostname & protocol for your site
#url: http://127.0.0.1:4000
twitter_username: jekyllrb
github_username:  jekyll



gmail: emmanabayabay@gmail.com
juliet_email: julietmariej.abayabay@yahoo.com
#gmail: iancabigon@gmail.com


# Build settings
markdown: kramdown

facebook: https://www.facebook.com/ERCAbayabayCustomsBrokerage
twitter: https://www.facebook.com/ERCAbayabayCustomsBrokerage

customs_site: http://customs.gov.ph/
portcallsasia_site: http://www.portcalls.com/
fande: http://fandegroup.wixsite.com/fandegroup/branches
savers_depot: http://saversdepot.com.ph/
matimco: http://matimco.com/
corbox: http://www.corbox.com/
ramtyres: http://www.corbox.com/
virginia: http://www.virginiafood.com.ph/
boral: https://www.usgboral.com/en_ph/
lracustomsbrokerage: http://lracustoms.com/
dof: http://www.dof.gov.ph/
tariffcom: http://www.tariffcommission.gov.ph/
ccbi: http://ccbi.org.ph
rotary: http://www.rccebufuente.org
altavistagolf: http://altavistagolfcebu.com/
cyclenautical: https://cyclenauticalforwa.wixsite.com/cnfi

plugins: 
  - jekyll-paginate

paginate: 4
paginate_path: "/news/page:num/"

destination: ../public

